language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t damunga/fibo-complex -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true damunga/fibo-complex npm test  

after_success:
  - docker build -t damunga/multi-client ./client 
  - docker build -t damunga/multi-nginx ./nginx 
  - docker build -t damunga/multi-server ./server
  - docker build -t damunga/multi-worker ./worker
   
